### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [jpkhawam/Nabu#40]
Currently the APKs at all your releases seem to identify as

    package: name='com.jpkhawam.nabu' versionCode='1' versionName='1.0'

thus appearing as a single version. Could you please fix that [in your `build.gradle`](https://github.com/jpkhawam/Nabu/blob/main/app/build.gradle#L12)? `versionCode` must always be increased with each release (as that's what Android uses internally to tell versions apart), `versionName` is what is shown to the user. So the current release should rahter have

```gradle
        versionCode 9
        versionName "0.9.0"
```

(assuming it is the 9th release – however, if starting with the next release you put anything bigger than 1 it would be fine – important part is just that it's bigger than with any previous release, no matter how much). Thanks in advance!

**Comment by jpkhawam** [comment]
Most definitely! I'll change it right now. Thanks for pointing that out. I'm wondering if I should change it to something different (lower than 0.9.0) as a handful of features are needed before a proper 1.0.0 could be released

**Comment by IzzySoft** [comment]
Wow, that was fast!

> Most definitely! I'll change it right now.

Great! I'm just at adding your app [to my repo](https://apt.izzysoft.de/fdroid). If an adjusted APK would be available within half an hour, I could replace it before it's being published. Use whatever `versionName` fits – and yes, it would indeed look a bit strange when now it comes as 1.0 being replaced tomorrow by a 0.x, but it wouldn't be the first new app having it that way :rofl:

**Comment by jpkhawam** [comment]
@IzzySoft 
- I can rebuild the apk now, do I need to do some special signing? last time i was building it there were some steps to sign the apk. 
- I also should point out that the pinning and alarm icons in notes currently don't do anything. If you want I can comment them out for now.

**Comment by IzzySoft** [comment]
The APK at 0.9.0 has been signed properly it seems (I always test with `apksigner verify`, and it approved of the APK – however I didn't check whose signing keys were being used). Just make sure to use the same signing keys for the following releases or users won't be able to update.

As for missing features: If you wish, I can send you a PR with [fastlane structures](https://gitlab.com/-/snippets/1895688) (metadata like screenshots, description etc). Then you can maintain them yourself and point out in the description whatever is needed (and also have per-release changelogs displayed prominently to the user). My updater would pull changes along then whenever a new release was being detected.

(as for the timing: the "half hour" pointed to the timing of my updater and its follow-up sync, which starts at around 5:30 pm UTC each day. I can send a manual sync anytime if needed)

**Comment by jpkhawam** [comment]
I've created a new keystore and stored it in a private repo to make sure it is stored safely. I will delete the old released apk and upload the new one. 

> As for missing features: If you wish, I can send you a PR with [fastlane structures](https://gitlab.com/-/snippets/1895688)

That would be amazing!

**Comment by IzzySoft** [comment]
> I've created a new keystore and stored it in a private repo to make sure it is stored safely. I will delete the old released apk and upload the new one.

Oops! Different keystore means the update would not fit anymore. Keeping my :crossed_fingers: the new release turns up in time, or I better disable the "old one" for now. Will keep my fingers on the trigger and :pray: …

Fastlane I'll prepare after that, as we now enter a critical 15min…

**Comment by jpkhawam** [comment]
I don't have the old keystore anymore, so I suggest you remove the old apk. This one I'll safely preserve so it is more reliable

**Comment by IzzySoft** [comment]
I'll remove the old APK for sure. I just struggle whether I shall disable the app's listing for now, or whether the replacement APK will become available in time :see_no_evil: No worries. I'll just disable it for now before the old APK is synced, and re-enable it whenever the new shows up. So no need to rush things.

**Comment by jpkhawam** [comment]
[published the newly signed apk](https://github.com/jpkhawam/Nabu/releases/tag/v0.7.0)

**Comment by IzzySoft** [comment]
Wow, on the minute :partying_face: Replaced. So it will go live in a couple of minutes now. You can already [grab a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link [there](https://apt.izzysoft.de/fdroid/index/apk/com.jpkhawam.nabu) from your Readme if you wish :smiley:

**Comment by jpkhawam** [comment]
Yay! 🥳 
> You can already [grab a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link [there](https://apt.izzysoft.de/fdroid/index/apk/com.jpkhawam.nabu)
that's really cool 😄 done!

**Comment by IzzySoft** [comment]
Great! And it's live now! Will just send out my [AndroidAppRain toot](https://floss.social/@IzzyOnDroid/109252911223818496), and then prepare the fastlane-PR.

Closing here now as the issue is solved (just 2 hours, that's a record time!!! :smiley:). Will be continued in the PR then.

**Comment by IzzySoft** [comment]
PS: forgot to mention the listing is live now :smiley:

**Comment by jpkhawam** [comment]
awesome! thank you for your help and your time 😄. I'm also planning to work more on the app now that I've graduated

**Comment by IzzySoft** [comment]
Oh, then congrats to graduation! :tada: :mortar_board:
