### ISSUE TITLE
create an icon for the app

### ISSUE THREAD

**Issue by jpkhawam** [jpkhawam/Nabu#44]

**Comment by Terkyz** [comment]
@jpkhawam I just upgraded to 0.7.1 and just saw the new icon, is it pure chance or did you base it on the icon of (also a notes app) [Notesnook](https://notesnook.com/)?

**Comment by jpkhawam** [comment]
I kinda did, I don't know how to design so I took an icon from the Papirus Icon Theme and changed the colors and scale a little. To be honest, I didn't think that I probably shouldn't use an icon from another app, in my mind I thought the icon theme is GPLv3 so that it would be fine.
I'll try to create a new icon asap

**Comment by Terkyz** [comment]
> @Terkyz I kinda did, I don't know how to design so I took an icon from the Papirus Icon Theme and changed the colors and scale a little. To be honest, I didn't think that I probably shouldn't use an icon from another app, in my mind I thought the icon theme is GPLv3 so that it would be fine. I'll try to create a new icon asap. If you have advice for software to use I'd appreciate that, I tried inkscape. I'll add I did mention this in the README

Mmmm, maybe I can help with that, mainly because I don't know how to program, but I can help with this. I will try to create something or give ideas and share them here.

**Comment by jpkhawam** [comment]
I would greatly appreciate that :) for now I'll do something random to avoid issues. Thanks for mentioning this issue btw

**Comment by jpkhawam** [comment]
I will replace the icon with this for now. Pushing an update within 10 minutes

**Comment by jpkhawam** [comment]
![Screenshot from 2022-11-02 23-04-55](https://user-images.githubusercontent.com/44164731/199604484-7a87e9e6-e9c3-4ef9-8ac5-98faef4412ad.png)
