### ISSUE TITLE
Empty trash

### ISSUE THREAD

**Issue by shuvashish76** [jpkhawam/Nabu#52]
Feature request for an option to empty trash with just 1 click _(of course show a confirmation dialog that all notes will be lost)_. Currently as of `v0.7.2 (9)` to do this user needs to manually select notes one by one which is annoying.

**Comment by jpkhawam** [comment]
if someone wants to work on this issue it's pretty easy. In `TrashActivity.java` you can call `dataBaseHelper.emptyTrash()`. Just have a button for that in the top bar with a confirmation preferably.

**Comment by adamtkac** [comment]
Hello may I work this issue?
